apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-app
#   namespace: my-namespace
#   labels:
#     app: my-app
# spec:
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 80
#     targetPort: http
#     protocol: TCP
#   selector:
#     app: my-app


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: app
          #image: brightbox/rails-hello-world
          image: docker.ingress.ddop.dcpgreendot.com:5003/petclinic:2.1.0.BUILD-SNAPSHOT0.1
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP