apiVersion: v1
kind: Namespace
metadata:
  name: pocep

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: pocep
  labels:
    app: petclinic
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: petclinic


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: pocep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: app
          #image: brightbox/rails-hello-world
          image: gcr.io/us-con-gcp-npr-0000266-072920/petclinic:2.1.0.BUILD-SNAPSHOT0.1
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
